CREATE TABLE IF NOT EXISTS "courses" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "courses_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"price" integer NOT NULL,
	"created-at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "teacher_to_courses" (
	"user_id" integer NOT NULL,
	"teacher_id" integer NOT NULL,
	"teacher_user_id" varchar NOT NULL,
	CONSTRAINT "teacher_to_courses_user_id_teacher_user_id_pk" PRIMARY KEY("user_id","teacher_user_id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "teachers" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "teachers_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"email" varchar(256) NOT NULL,
	"user-id" varchar NOT NULL,
	"pricing" integer NOT NULL,
	"created-at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updated_at" timestamp with time zone,
	CONSTRAINT "teachers_user-id_unique" UNIQUE("user-id")
);
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "teacher_to_courses" ADD CONSTRAINT "teacher_to_courses_user_id_courses_id_fk" FOREIGN KEY ("user_id") REFERENCES "public"."courses"("id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "teacher_to_courses" ADD CONSTRAINT "teacher_to_courses_teacher_id_teachers_id_fk" FOREIGN KEY ("teacher_id") REFERENCES "public"."teachers"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "teacher_to_courses" ADD CONSTRAINT "teacher_to_courses_teacher_user_id_teachers_user-id_fk" FOREIGN KEY ("teacher_user_id") REFERENCES "public"."teachers"("user-id") ON DELETE cascade ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "courses_name_index" ON "courses" USING btree ("name");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "teacher_name_idx" ON "teachers" USING btree ("email");--> statement-breakpoint
CREATE INDEX IF NOT EXISTS "teacher_userid-idx" ON "teachers" USING btree ("user-id");
