DO $$ BEGIN
 CREATE TYPE "public"."role" AS ENUM('admin', 'student');
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "user-course" (
	"user-id" integer NOT NULL,
	"id" integer NOT NULL,
	"user-clerk-id" varchar NOT NULL,
	CONSTRAINT "user-course_user-id_id_pk" PRIMARY KEY("user-id","id")
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar NOT NULL,
	"email" varchar NOT NULL,
	"username" varchar,
	"image" varchar,
	"clerk-user-id" varchar NOT NULL,
	"role" "role",
	CONSTRAINT "users_email_unique" UNIQUE("email"),
	CONSTRAINT "users_clerk-user-id_unique" UNIQUE("clerk-user-id")
);
--> statement-breakpoint
DROP TABLE "teacher_to_courses";--> statement-breakpoint
DROP TABLE "teachers";--> statement-breakpoint
ALTER TABLE "courses" ADD COLUMN "pricing" integer NOT NULL;--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "user-course" ADD CONSTRAINT "user-course_user-id_users_id_fk" FOREIGN KEY ("user-id") REFERENCES "public"."users"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "user-course" ADD CONSTRAINT "user-course_id_courses_id_fk" FOREIGN KEY ("id") REFERENCES "public"."courses"("id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
DO $$ BEGIN
 ALTER TABLE "user-course" ADD CONSTRAINT "user-course_user-clerk-id_users_clerk-user-id_fk" FOREIGN KEY ("user-clerk-id") REFERENCES "public"."users"("clerk-user-id") ON DELETE no action ON UPDATE no action;
EXCEPTION
 WHEN duplicate_object THEN null;
END $$;
--> statement-breakpoint
ALTER TABLE "courses" DROP COLUMN IF EXISTS "price";